---
title: "CSE3506_PROJECT"
author: "KEERTHANA S_20BCE1049"
date: "2022-12-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Predicting Hit Songs**

## Dataset

```{r}
#Loading dataset
data_sixties = read.csv("dataset-of-60s.csv")
head(data_sixties)
data_seventies = read.csv("dataset-of-70s.csv")
head(data_seventies)
data_eighties = read.csv("dataset-of-80s.csv")
head(data_eighties)
data_nineties = read.csv("dataset-of-90s.csv")
head(data_nineties)
data_twentieth = read.csv("dataset-of-00s.csv")
head(data_twentieth)
data_twentieth_1 = read.csv("dataset-of-10s.csv")
head(data_twentieth_1)
```
## Combining all the dataframes into a single dataset

```{r}
data = rbind(data_sixties, data_seventies, data_eighties, data_nineties, data_twentieth, data_twentieth_1)
write.csv(data,"combined_data.csv")
data = read.csv("combined_data.csv")
```
## Understanding the dataset

```{r}
dim(data)
str(data)
summary(data)
```

```{r}
na_data = data[!complete.cases(data), ]
dim(na_data)
```
From above, we can infer that there are no records with NA values

```{r}
#Checking for duplicate records
dup = data[duplicated(data), ]
dim(dup)
```
```{r}
#Removing the duplicate values from dataset
data = data[!duplicated(data), ]
dim(data)
```
## Converting categorical data into numerical data

```{r}
artists = data$artist
#find number of values in artists
length(artists)
#find all unique values in artists
unique_artists = unique(artists)
length(unique_artists)
#map all unique artists to a number
artist_map = as.data.frame(unique_artists)
artist_map$artist_id = 1:nrow(artist_map)
head(artist_map)
length(unique_artists)
#replace artist names with artist ids
data$artist = as.character(data$artist)
for(i in 1:nrow(data)){
  data$artist[i] = artist_map$artist_id[artist_map$unique_artists == data$artist[i]]
}
head(data)
```
## Feature Selection
```{r}

```




